In [1]:
import sys

import tensorflow.keras
import pandas as pd
import sklearn as sk
import tensorflow as tf
tf.config.list_physical_devices('GPU')
print(f"Tensor Flow Version: {tf.__version__}")
print(f"Keras Version: {tensorflow.keras.__version__}")
print()
print(f"Python {sys.version}")
print(f"Pandas {pd.__version__}")
print(f"Scikit-Learn {sk.__version__}")
print("GPU is", "available" if tf.test.is_gpu_available()
     else "NOT AVAILABLE")

Tensor Flow Version: 2.1.0
Keras Version: 2.2.4-tf

Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]
Pandas 1.0.1
Scikit-Learn 0.22.1
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
GPU is available


In [2]:
X = tf.ones(shape=(2, 1))
print(X)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [4]:
X = tf.zeros(shape=(2, 1))
print(X)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [5]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[0.51944244]
 [0.67145574]
 [0.70556533]], shape=(3, 1), dtype=float32)


In [8]:
import numpy as np
x = np.ones(shape=(2, 2))
print(x)

[[1. 1.]
 [1. 1.]]


In [9]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.20634781],
       [ 1.3386326 ],
       [-0.5382727 ]], dtype=float32)>


In [10]:
v.assign(tf.ones((3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>
